---
version: '3.4'
services:
  angularapp:
    container_name: angularapp
    image: angularapp:1.0.0
    build:
      context: ./angfrontend
      dockerfile: angular.Dockerfile
    ports:
      - 80:80
    depends_on:
      - flaskapp
  flaskapp: 
    container_name: flaskapp
    image: flaskapp:1.0.0
    build:
      context: ./backend
      dockerfile: flask.Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - weaviate
    env_file: .env.backend
  weaviate:
    container_name: weaviate
    volumes:
      - weaviate-data:/var/lib/weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.20.3
    ports:
    - 8080:8080    
    restart: on-failure:0
    env_file: .env.weaviate
     
volumes:
  weaviate-data: 
    external: true
...